services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: invoices
      POSTGRES_PASSWORD: invoices
      POSTGRES_DB: invoices_db
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  db_data: