DROP TABLE IF EXISTS T_INVOICE_DETAILS;

CREATE TABLE T_INVOICE_DETAILS (
    IND_ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    IND_PROD_NAME CHARACTER VARYING(255) NOT NULL,
    IND_QUANTITY BIGINT NOT NULL,
    IND_UNIT_PRICE NUMERIC(10, 2) NOT NULL,
    IND_SUB_TOTAL NUMERIC(10, 2) NOT NULL,
    IND_INH_ID BIGINT NOT NULL,
    CONSTRAINT PK_T_INVOICE_DETAILS_IND_ID PRIMARY KEY (IND_ID),
    CONSTRAINT FK_T_INVOICE_DETAILS_IND_INH_ID FOREIGN KEY (IND_INH_ID)
        REFERENCES T_INVOICE_HEADERS (INH_ID)
        ON DELETE CASCADE
);